name: Docker Build Develop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # docker hub의 organization 이름
  REGISTRY: haesummy
  # build and push 할 docker image 이름
  IMAGE_NAME: monnani-ai
  # build and push 할 docker image의 tag
  TAG: 7
  IS_PUSH: ${{ github.event_name != 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodules
        uses: actions/checkout@v3

      - name: Login to DockerHub
        if: ${{ env.IS_PUSH }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push the Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
